// Code generated by bpf2go; DO NOT EDIT.

package gtpu

import (
	"bytes"
	_ "embed"
	"fmt"
	"io"
	"structs"

	"github.com/cilium/ebpf"
)

type GtpuEncapIpv4Key struct {
	_    structs.HostLayout
	Addr [4]uint8
}

type GtpuEncapTftRuleEntry struct {
	_            structs.HostLayout
	UlTeid       uint32
	Precedence   uint8
	Flags        uint8
	Protocol     uint8
	Pad          uint8
	RemoteIp     [4]uint8
	RemoteMask   [4]uint8
	LocalPortLo  uint16
	LocalPortHi  uint16
	RemotePortLo uint16
	RemotePortHi uint16
}

type GtpuEncapTftRuleKey struct {
	_     structs.HostLayout
	Addr  [4]uint8
	Index uint32
}

type GtpuEncapUeSessionEntry struct {
	_          structs.HostLayout
	UlTeid     uint32
	PgwIp      [4]uint8
	LocalIp    [4]uint8
	S2bIfindex uint32
	RuleCount  uint32
}

// LoadGtpuEncap returns the embedded CollectionSpec for GtpuEncap.
func LoadGtpuEncap() (*ebpf.CollectionSpec, error) {
	reader := bytes.NewReader(_GtpuEncapBytes)
	spec, err := ebpf.LoadCollectionSpecFromReader(reader)
	if err != nil {
		return nil, fmt.Errorf("can't load GtpuEncap: %w", err)
	}

	return spec, err
}

// LoadGtpuEncapObjects loads GtpuEncap and converts it into a struct.
//
// The following types are suitable as obj argument:
//
//	*GtpuEncapObjects
//	*GtpuEncapPrograms
//	*GtpuEncapMaps
//
// See ebpf.CollectionSpec.LoadAndAssign documentation for details.
func LoadGtpuEncapObjects(obj interface{}, opts *ebpf.CollectionOptions) error {
	spec, err := LoadGtpuEncap()
	if err != nil {
		return err
	}

	return spec.LoadAndAssign(obj, opts)
}

// GtpuEncapSpecs contains maps and programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type GtpuEncapSpecs struct {
	GtpuEncapProgramSpecs
	GtpuEncapMapSpecs
	GtpuEncapVariableSpecs
}

// GtpuEncapProgramSpecs contains programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type GtpuEncapProgramSpecs struct {
	TcGtpuEncapFunc *ebpf.ProgramSpec `ebpf:"tc_gtpu_encap_func"`
}

// GtpuEncapMapSpecs contains maps before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type GtpuEncapMapSpecs struct {
	TftRuleMap   *ebpf.MapSpec `ebpf:"tft_rule_map"`
	UeSessionMap *ebpf.MapSpec `ebpf:"ue_session_map"`
	UlStats      *ebpf.MapSpec `ebpf:"ul_stats"`
}

// GtpuEncapVariableSpecs contains global variables before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type GtpuEncapVariableSpecs struct {
}

// GtpuEncapObjects contains all objects after they have been loaded into the kernel.
//
// It can be passed to LoadGtpuEncapObjects or ebpf.CollectionSpec.LoadAndAssign.
type GtpuEncapObjects struct {
	GtpuEncapPrograms
	GtpuEncapMaps
	GtpuEncapVariables
}

func (o *GtpuEncapObjects) Close() error {
	return _GtpuEncapClose(
		&o.GtpuEncapPrograms,
		&o.GtpuEncapMaps,
	)
}

// GtpuEncapMaps contains all maps after they have been loaded into the kernel.
//
// It can be passed to LoadGtpuEncapObjects or ebpf.CollectionSpec.LoadAndAssign.
type GtpuEncapMaps struct {
	TftRuleMap   *ebpf.Map `ebpf:"tft_rule_map"`
	UeSessionMap *ebpf.Map `ebpf:"ue_session_map"`
	UlStats      *ebpf.Map `ebpf:"ul_stats"`
}

func (m *GtpuEncapMaps) Close() error {
	return _GtpuEncapClose(
		m.TftRuleMap,
		m.UeSessionMap,
		m.UlStats,
	)
}

// GtpuEncapVariables contains all global variables after they have been loaded into the kernel.
//
// It can be passed to LoadGtpuEncapObjects or ebpf.CollectionSpec.LoadAndAssign.
type GtpuEncapVariables struct {
}

// GtpuEncapPrograms contains all programs after they have been loaded into the kernel.
//
// It can be passed to LoadGtpuEncapObjects or ebpf.CollectionSpec.LoadAndAssign.
type GtpuEncapPrograms struct {
	TcGtpuEncapFunc *ebpf.Program `ebpf:"tc_gtpu_encap_func"`
}

func (p *GtpuEncapPrograms) Close() error {
	return _GtpuEncapClose(
		p.TcGtpuEncapFunc,
	)
}

func _GtpuEncapClose(closers ...io.Closer) error {
	for _, closer := range closers {
		if err := closer.Close(); err != nil {
			return err
		}
	}
	return nil
}

// Do not access this directly.
//
//go:embed gtpuencap_bpf.o
var _GtpuEncapBytes []byte
