// Code generated by bpf2go; DO NOT EDIT.

package gtpu

import (
	"bytes"
	_ "embed"
	"fmt"
	"io"
	"structs"

	"github.com/cilium/ebpf"
)

type GtpuDecapTeidEntry struct {
	_   structs.HostLayout
	Paa [4]uint8
}

// LoadGtpuDecap returns the embedded CollectionSpec for GtpuDecap.
func LoadGtpuDecap() (*ebpf.CollectionSpec, error) {
	reader := bytes.NewReader(_GtpuDecapBytes)
	spec, err := ebpf.LoadCollectionSpecFromReader(reader)
	if err != nil {
		return nil, fmt.Errorf("can't load GtpuDecap: %w", err)
	}

	return spec, err
}

// LoadGtpuDecapObjects loads GtpuDecap and converts it into a struct.
//
// The following types are suitable as obj argument:
//
//	*GtpuDecapObjects
//	*GtpuDecapPrograms
//	*GtpuDecapMaps
//
// See ebpf.CollectionSpec.LoadAndAssign documentation for details.
func LoadGtpuDecapObjects(obj interface{}, opts *ebpf.CollectionOptions) error {
	spec, err := LoadGtpuDecap()
	if err != nil {
		return err
	}

	return spec.LoadAndAssign(obj, opts)
}

// GtpuDecapSpecs contains maps and programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type GtpuDecapSpecs struct {
	GtpuDecapProgramSpecs
	GtpuDecapMapSpecs
	GtpuDecapVariableSpecs
}

// GtpuDecapProgramSpecs contains programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type GtpuDecapProgramSpecs struct {
	GtpuDecapFunc *ebpf.ProgramSpec `ebpf:"gtpu_decap_func"`
}

// GtpuDecapMapSpecs contains maps before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type GtpuDecapMapSpecs struct {
	ConfigMap *ebpf.MapSpec `ebpf:"config_map"`
	DlStats   *ebpf.MapSpec `ebpf:"dl_stats"`
	TeidMap   *ebpf.MapSpec `ebpf:"teid_map"`
}

// GtpuDecapVariableSpecs contains global variables before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type GtpuDecapVariableSpecs struct {
}

// GtpuDecapObjects contains all objects after they have been loaded into the kernel.
//
// It can be passed to LoadGtpuDecapObjects or ebpf.CollectionSpec.LoadAndAssign.
type GtpuDecapObjects struct {
	GtpuDecapPrograms
	GtpuDecapMaps
	GtpuDecapVariables
}

func (o *GtpuDecapObjects) Close() error {
	return _GtpuDecapClose(
		&o.GtpuDecapPrograms,
		&o.GtpuDecapMaps,
	)
}

// GtpuDecapMaps contains all maps after they have been loaded into the kernel.
//
// It can be passed to LoadGtpuDecapObjects or ebpf.CollectionSpec.LoadAndAssign.
type GtpuDecapMaps struct {
	ConfigMap *ebpf.Map `ebpf:"config_map"`
	DlStats   *ebpf.Map `ebpf:"dl_stats"`
	TeidMap   *ebpf.Map `ebpf:"teid_map"`
}

func (m *GtpuDecapMaps) Close() error {
	return _GtpuDecapClose(
		m.ConfigMap,
		m.DlStats,
		m.TeidMap,
	)
}

// GtpuDecapVariables contains all global variables after they have been loaded into the kernel.
//
// It can be passed to LoadGtpuDecapObjects or ebpf.CollectionSpec.LoadAndAssign.
type GtpuDecapVariables struct {
}

// GtpuDecapPrograms contains all programs after they have been loaded into the kernel.
//
// It can be passed to LoadGtpuDecapObjects or ebpf.CollectionSpec.LoadAndAssign.
type GtpuDecapPrograms struct {
	GtpuDecapFunc *ebpf.Program `ebpf:"gtpu_decap_func"`
}

func (p *GtpuDecapPrograms) Close() error {
	return _GtpuDecapClose(
		p.GtpuDecapFunc,
	)
}

func _GtpuDecapClose(closers ...io.Closer) error {
	for _, closer := range closers {
		if err := closer.Close(); err != nil {
			return err
		}
	}
	return nil
}

// Do not access this directly.
//
//go:embed gtpudecap_bpf.o
var _GtpuDecapBytes []byte
